In [1]:
import torch

In [64]:
y = torch.Tensor([[float('NaN'), float('NaN'),1, 2, 3],[5, 8, 4, float('NaN'), 3]])
x = torch.Tensor([[2, 1, 4, 2, 4],[5, 8, 4, 2 ,4]])

In [65]:
y != y

tensor([[1, 1, 0, 0, 0],
        [0, 0, 0, 1, 0]], dtype=torch.uint8)

In [70]:
y[y==y]

tensor([1., 2., 3., 5., 8., 4., 3.])

In [67]:
x[y==y]

tensor([4., 2., 4., 5., 8., 4., 4.])

In [71]:
criterion = torch.nn.MSELoss()

In [72]:
criterion(y[y==y],x[y==y])

tensor(1.5714)